### ISSUE TITLE
Convert each page to html, join the html, then convert to PDF

### ISSUE THREAD

**Issue by kohheepeace** [kohheepeace/mr-pdf#10]
Borrow the @bojl idea of this [PR](https://github.com/kohheepeace/docusaurus-pdf/pull/27) for making internal links work.

**Comment by covalentbond** [comment]
Hey @kohheepeace, we've been using `mr-pdf` for generating the Docusaurus PDF of version `v2.0.0beta-0`. Will this issue solve the following issue? Or a new issue needs to be created?

But internal links have not been working.

You can find the PDF of https://zowe-docs.netlify.app/ ([here](https://zowe-docs.netlify.app/zowe-docs.pdf)).
For reproducing the issue. 

- Go to page 12, the internal links are not working. The text present as TOC are unclickable.

![image](https://user-images.githubusercontent.com/53327173/120178176-d3081480-c226-11eb-9e0e-860b6cc3c2b3.png)

- Go to page 84, **Configuring z/OSMF Lite (for nonproduction use)** text redirect to http://localhost:3000/stable/user-guide/systemrequirements-zosmf-lite on deployed version. When the PDF is produced through `--initialDocsURL="http://localhost:3000/stable/getting-started/overview"`.
- When the PDF is produced through `--initialDocsURL="https://zowe-docs.netlify.app/stable/getting-started/overview"`. It redirects to https://zowe-docs.netlify.app/stable/user-guide/systemrequirements-zosmf-lite/. 

![image](https://user-images.githubusercontent.com/53327173/120179866-bff64400-c228-11eb-8683-17146746612d.png)



In both the cases it should redirect to the user to the section in the PDF only - not to the online version?

**Comment by kohheepeace** [comment]
@covalentbond I will check👍

**Comment by kohheepeace** [comment]
@covalentbond I confirmed that internal link works well after fixing this issue. I will PR in a week.

**Comment by covalentbond** [comment]
Thanks @kohheepeace looking forward for the fix!

Apart from this issue, I encountered another issue that:

In https://zowe-docs.netlify.app/ we are having different sections like "Get Started", "User Guide", "Extend"...
But while running the script with `--initialDocsURL="https://zowe-docs.netlify.app/stable/getting-started/overview`. The [PDF generated](https://zowe-docs.netlify.app/zowe-docs.pdf) contains only "Getting Started" section - not the complete documentation. How to include all the other sections as well?

**Comment by kohheepeace** [comment]
@covalentbond I came up with the idea to make multiple sections. I will tackle it.👍

**Comment by covalentbond** [comment]
Sure, waiting for these fixes. Just FYI I'm also at the end of an internship, where fixing this would mostly complete it. The completion is also imp for my resume. 😂

**Comment by covalentbond** [comment]
Sure, waiting for these fixes. Just FYI I'm also at the end of an internship, where fixing this PDF functionality would mostly complete all the task. The completion is also imp for my resume. 😂

**Comment by kohheepeace** [comment]
@covalentbond I just implemented the feature👍

**Comment by covalentbond** [comment]
@kohheepeace the links present in the TOC are working.

But links refering to other internal doc is still not working. The second and third issue mentioned in this [comment](https://github.com/kohheepeace/mr-pdf/issues/10#issuecomment-851393000) still exits.

For eg. This is a line present in any docs `For more information, see [Installing Zowe SMP/E Alpha](../user-guide/install-zowe-smpe.md).` This kind of link is still not working. Please look into it.

**Comment by kohheepeace** [comment]
@covalentbond Thanks that it true 👍
